In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Add
from tensorflow.keras.layers import Convolution2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.datasets import mnist


In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
print (X_train.shape)
from matplotlib import pyplot as plt
%matplotlib inline
plt.imshow(X_train[0])

In [4]:
X_train = X_train.reshape(X_train.shape[0], 28, 28,1)
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [5]:
# Convert 1-dimensional class arrays to 10-dimensional class matrices
Y_train = to_categorical(y_train, 10)
Y_test = to_categorical(y_test, 10)

In [6]:
Y_train[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [7]:
Y_test[:10]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Activation
model = Sequential()

# model.add(Convolution2D(128, 3, 3, activation='relu', input_shape=(28,28,1)))
# # model.add(Convolution2D(10, 1, activation='relu'))
# # model.add(Convolution2D(10, 26))
# model.add(Convolution2D(256,3,3, activation='relu'))
# model.add(MaxPooling2D(pool_size=(2,2)))
# model.add(Convolution2D(512,3,3, activation='relu'))
# model.add(Convolution2D(1024,3,3, activation='relu'))
# model.add(Convolution2D(10,1,activation='relu'))
# model.add(Convolution2D(10,8))
# model.add(Flatten())
# model.add(Activation('softmax'))
model.add(Convolution2D(128, (3, 3), activation = 'relu', input_shape = (28, 28, 1)))
model.add(Convolution2D(256, (3, 3), activation = 'relu'))
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.5))
model.add(Convolution2D(512, (3, 3), activation = 'relu'))
model.add(Convolution2D(1024, (3, 3), activation = 'relu'))
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.5))
model.add(Convolution2D(1024, (3, 3), activation = 'relu'))
model.add(Flatten())
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.5))
# model.add(Flatten())
model.add(Dense(10, activation = 'softmax'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 128)       1280      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 256)       295168    
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 256)       0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 256)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 10, 10, 512)       1180160   
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 8, 8, 1024)        4719616   
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 1024)        0

In [10]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])


In [12]:
model.fit(X_train, Y_train, batch_size=120, epochs=20, verbose=1)

Epoch 1/20
500/500 [==============================] - 61s 123ms/step - loss: 0.2123 - accuracy: 0.9309
Epoch 2/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0546 - accuracy: 0.9844
Epoch 3/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0443 - accuracy: 0.9874
Epoch 4/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0344 - accuracy: 0.9902
Epoch 5/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0307 - accuracy: 0.9911
Epoch 6/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0270 - accuracy: 0.9919
Epoch 7/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0259 - accuracy: 0.9924
Epoch 8/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0237 - accuracy: 0.9934
Epoch 9/20
500/500 [==============================] - 62s 123ms/step - loss: 0.0206 - accuracy: 0.9938
Epoch 10/20
500/500 [==============================] - 62s 123ms/step - l

In [13]:
score = model.evaluate(X_test, Y_test, verbose=0)
print(score)

[0.03730804845690727, 0.9926000237464905]


In [14]:
y_pred = model.predict(X_test)
print(y_pred[:9])
print(y_test[:9])

[[1.22326820e-31 1.59541569e-19 2.07244710e-21 1.15663760e-19
  5.96748649e-18 1.24608686e-24 7.57272230e-35 1.00000000e+00
  2.78955455e-24 7.10754693e-18]
 [7.74751094e-21 1.77702152e-17 1.00000000e+00 3.87897806e-15
  3.91107699e-20 6.01237973e-20 1.03277609e-13 1.14533466e-14
  4.60898646e-14 1.94095676e-23]
 [1.84507762e-24 1.00000000e+00 6.79290816e-21 9.15207136e-25
  1.41147929e-16 2.44716395e-19 2.72224296e-17 2.37294278e-17
  2.42206424e-16 9.79787762e-22]
 [1.00000000e+00 4.93424691e-13 1.31882867e-13 5.81031126e-11
  1.68041481e-12 9.03457604e-12 1.19183763e-09 8.79353274e-12
  1.30210096e-11 1.12018686e-10]
 [3.75790608e-19 2.37639932e-13 1.69693442e-16 2.10046129e-15
  1.00000000e+00 3.59821290e-15 1.11696939e-14 1.07325383e-13
  3.03213748e-12 3.08106353e-11]
 [1.61362280e-29 1.00000000e+00 1.83358470e-24 8.93387067e-30
  1.76382333e-19 2.51669259e-25 1.01295476e-21 3.36790981e-19
  3.50142936e-20 2.62379377e-25]
 [1.56509361e-28 4.14326795e-17 3.95684325e-22 5.26807771e